name: Tests

on: [push]

jobs:
  brakeman:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
    name: Ruby ${{ matrix.ruby }} tests
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - run: bundle exec rake test
